[versions]

kotlin = "1.7.21"
application = "7.4.0"
library = "7.4.0"

coreKtx = "1.7.0"
appCompat = "1.4.1"
activityKtx = "1.4.0"
fragmentKtx = "1.4.1"
material = "1.6.0"
constraintLayout = "2.1.4"
recyclerView = "1.2.1"
coroutines = "1.6.1"

timber = "5.0.1"
calendar = "2.0.1"
hilt = "2.42"
splashscreen = "1.0.0-rc01"
glide = "4.13.2"
lifecycle = "2.4.1"
playServices = "4.3.10"

junit = "4.13.2"
junitext = "1.1.3"
assertj = "3.11.1"
mockk = "1.13.5"
jodaTime = "2.10.6"
espresso = "3.4.0"

interceptor = "4.9.3"
kakao = "2.13.0"
lottie = "5.2.0"
datastore = "1.0.0"
firebase = "31.2.3"
room = "2.5.0"

bom = "2023.10.01"
activityCompose = "1.8.2"
lifecycleCompose = "2.6.2"
navigationCompose = "2.7.6"
glideCompose = "1.0.0-beta01"

splash = "1.0.0"
retrofit = "2.9.0"

MPAndroidChart = "v3.1.0"

playServicesLocation = "16.0.0"

navermap = "3.16.0"

swiprefesh = "1.5.1"

googleServices = "4.3.15"

detekt = "1.23.0"
androidx-test-ext-junit = "1.1.5"
